spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/user?&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
    druid:
      initial-size: 5
#      最大连接词
      max-active: 20
#      获取连接最大等大时间
      max-wait: 50000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
      filters: stat,wall,log4j
  #如果允许时报错 java.lang.ClassNotFoundException:

  #则导入 log4j 依赖即可，Maven 地址：

#      filters: stat,wall,log4j
#      maxPoolPreparedStatementPerConnectionSize: 20
#      useGlobalDataSourceStat: true
#      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
server:
  port: 8081
mybatis-plus:
  mapper-locations: classpath:Mapper/*.xml
